baseURL = "https://jayIsThere.github.io/zusammenfassung/"
languageCode = "en-us"
title = "Jays Zusammenfassung"
theme = "PaperMod"



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

          
[params]
  homeInfoParams = { Title = "Zusammenfassung", Content = "Jays Zusammenfassung" }
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  math = true
  socialShare = false

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = "categories"
  url = "/categories/"
  weight = 10
  identifier = "categories"

[[menu.main]]
  name = "tags"
  url = "/tags/"
  weight = 20
  identifier = "tags"

[[menu.main]]
  name = "example.org"
  url = "https://example.org"
  weight = 30
  identifier = "example"

